CC=gcc
CFLAGS= -c -Wall
#CFLAGS+= -g
#CFLAGS+= -D PRODUCTION -O3 -Werror
#CFLAGS+= -D PRODUCTION -D BENCHMARKING -D BENCHMARKING_RUNS=10 -O0
#CFLAGS+= -D PRODUCTION -D BENCHMARKING -D BENCHMARKING_RUNS=10 -O1
#CFLAGS+= -D PRODUCTION -D BENCHMARKING -D BENCHMARKING_RUNS=10 -O2
#CFLAGS+= -D PRODUCTION -D BENCHMARKING -D BENCHMARKING_RUNS=10 -O3
SOURCES=28bit.c
OBJECTS=28bit.o
EXECUTABLE=28bit

all: $(EXECUTABLE)

clean:
	-rm $(OBJECTS) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(OBJECTS) -o $@

.c.o:
	$(CC) $(CFLAGS) $< -o $@
